                    List of relations
 Schema |             Name             | Type  |  Owner   
--------+------------------------------+-------+----------
 public | addresses                    | table | bitadmin
 public | asset                        | table | bitadmin
 public | balance                      | table | bitadmin
 public | banner                       | table | bitadmin
 public | casbin_rule                  | table | bitadmin
 public | category                     | table | bitadmin
 public | category_language            | table | bitadmin
 public | chain                        | table | bitadmin
 public | currencies                   | table | bitadmin
 public | deposit                      | table | bitadmin
 public | ecosystem                    | table | bitadmin
 public | ecosystem_language           | table | bitadmin
 public | event                        | table | bitadmin
 public | event_language               | table | bitadmin
 public | event_period                 | table | bitadmin
 public | event_period_language        | table | bitadmin
 public | event_result_period          | table | bitadmin
 public | exchange_rate_current        | table | bitadmin
 public | exchange_rate_history        | table | bitadmin
 public | exchange_rate_platform       | table | bitadmin
 public | languages                    | table | bitadmin
 public | orders                       | table | bitadmin
 public | split_merge_record           | table | bitadmin
 public | sub_event                    | table | bitadmin
 public | sub_event_chance_stat        | table | bitadmin
 public | sub_event_direction          | table | bitadmin
 public | sub_event_direction_language | table | bitadmin
 public | sub_event_language           | table | bitadmin
 public | sub_order                    | table | bitadmin
 public | sys_apis                     | table | bitadmin
 public | sys_dicts                    | table | bitadmin
 public | sys_funding_stats            | table | bitadmin
 public | sys_menus                    | table | bitadmin
 public | sys_order_stats              | table | bitadmin
 public | sys_pnl_stats                | table | bitadmin
 public | sys_records                  | table | bitadmin
 public | sys_risk_stats               | table | bitadmin
 public | sys_role_apis                | table | bitadmin
 public | sys_role_auths               | table | bitadmin
 public | sys_roles                    | table | bitadmin
 public | sys_stats                    | table | bitadmin
 public | sys_users                    | table | bitadmin
 public | team_group                   | table | bitadmin
 public | team_group_language          | table | bitadmin
 public | team_type                    | table | bitadmin
 public | team_type_language           | table | bitadmin
 public | user_biggest_wins_rank       | table | bitadmin
 public | user_blacklist               | table | bitadmin
 public | user_event_comment           | table | bitadmin
 public | user_event_position          | table | bitadmin
 public | user_event_profit            | table | bitadmin
 public | user_event_profit_stat       | table | bitadmin
 public | user_leaderboard_rank        | table | bitadmin
 public | users                        | table | bitadmin
 public | withdraw                     | table | bitadmin
 public | withdraw_review              | table | bitadmin
(56 rows)

